spring.application.name=sql-intro

spring.datasource.url=jdbc:postgresql://localhost:5432/kutuphanesistemi2
spring.datasource.username=postgres
spring.datasource.password=0701
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none